#!/bin/bash -l
# conda env providing R
CONDA_ENV=r-40

module load conda
conda activate ${CONDA_ENV}

export RETICULATE_PYTHON="$CONDA_PREFIX/bin/python"
export LD_LIBRARY_PATH="$CONDA_PREFIX/lib/R/lib:$CONDA_PREFIX/lib:$LD_LIBRARY_PATH"

module load rstudio-server
exec rsession \
    --session-create-public-folder=1 \
    --www-address=127.0.0.1 \
    $@
